name: Deploy to AWS

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@master
        with:
          host: \${{ secrets.AWS_HOST }}
          username: \${{ secrets.AWS_USER }}
          key: \${{ secrets.AWS_SSH_KEY }}
          script: |
            cd estagio-supervisionado-monorepo/estagio-supervisionado-lionfitess-frontend/lionfitness-frontend
            git pull origin master
            npm install
            npm run build
            pm2 restart lion-frontend || PORT=3000 nohup npm run start &
