
INSERT INTO exercise_catalog (id, name, category, muscle, equipment, instructions, is_custom, is_active, created_at) SELECT gen_random_uuid(), 'Supino Reto', 'Peito', 'Peitoral', 'Barra', 'Deite no banco plano com os pés apoiados no chão. Segure a barra com pegada pronada um pouco mais larga que os ombros. Desça a barra de forma controlada até tocar levemente o peito e empurre de volta à posição inicial, contraindo o peitoral. Mantenha a lombar neutra durante o movimento.', false, true, NOW() WHERE NOT EXISTS (SELECT 1 FROM exercise_catalog WHERE name = 'Supino Reto' AND category = 'Peito' AND is_custom = false);

INSERT INTO exercise_catalog (id, name, category, muscle, equipment, instructions, is_custom, is_active, created_at) SELECT gen_random_uuid(), 'Supino Inclinado', 'Peito', 'Peitoral', 'Barra e banco inclinado', 'Ajuste o banco a 30-45 graus. Deite com os pés apoiados no chão, segure a barra com pegada larga. Desça até a parte superior do peito e empurre de volta. O movimento inclinado enfatiza a porção clavicular do peitoral.', false, true, NOW() WHERE NOT EXISTS (SELECT 1 FROM exercise_catalog WHERE name = 'Supino Inclinado' AND category = 'Peito' AND is_custom = false);

INSERT INTO exercise_catalog (id, name, category, muscle, equipment, instructions, is_custom, is_active, created_at) SELECT gen_random_uuid(), 'Supino Declinado', 'Peito', 'Peitoral', 'Barra e banco declinado', 'Deite no banco declinado com os pés presos no suporte. Segure a barra e desça até a parte inferior do peito. Empurre de volta à posição inicial. Enfatiza a porção esternal inferior do peitoral e trabalha o peitoral maior com maior amplitude.', false, true, NOW() WHERE NOT EXISTS (SELECT 1 FROM exercise_catalog WHERE name = 'Supino Declinado' AND category = 'Peito' AND is_custom = false);

INSERT INTO exercise_catalog (id, name, category, muscle, equipment, instructions, is_custom, is_active, created_at) SELECT gen_random_uuid(), 'Crucifixo Reto com Halteres', 'Peito', 'Peitoral', 'Halteres', 'Deite no banco plano, segure os halteres com os braços estendidos acima do peito. Com cotovelos levemente flexionados, abra os braços em arco amplo até sentir o alongamento no peitoral. Feche de volta contraindo o peitoral. Não use cargas excessivas para preservar os ombros.', false, true, NOW() WHERE NOT EXISTS (SELECT 1 FROM exercise_catalog WHERE name = 'Crucifixo Reto com Halteres' AND category = 'Peito' AND is_custom = false);

INSERT INTO exercise_catalog (id, name, category, muscle, equipment, instructions, is_custom, is_active, created_at) SELECT gen_random_uuid(), 'Crossover Polia Alta', 'Peito', 'Peitoral', 'Polia', 'Posicione as polias acima dos ombros e segure uma alça em cada mão. Dê um passo à frente para afastar o centro. Puxe os cabos para frente e para baixo, cruzando as mãos na frente do abdômen. Contraia o peitoral no final e retorne controlado. Ótimo para finalização e definição.', false, true, NOW() WHERE NOT EXISTS (SELECT 1 FROM exercise_catalog WHERE name = 'Crossover Polia Alta' AND category = 'Peito' AND is_custom = false);

INSERT INTO exercise_catalog (id, name, category, muscle, equipment, instructions, is_custom, is_active, created_at) SELECT gen_random_uuid(), 'Crossover Polia Baixa', 'Peito', 'Peitoral', 'Polia', 'Posicione as polias na altura do quadril ou abaixo. Segure as alças e puxe os cabos para frente e para cima, cruzando na frente do peito. Contraia o peitoral superior ao longo do movimento. Enfatiza a porção clavicular do peitoral.', false, true, NOW() WHERE NOT EXISTS (SELECT 1 FROM exercise_catalog WHERE name = 'Crossover Polia Baixa' AND category = 'Peito' AND is_custom = false);

INSERT INTO exercise_catalog (id, name, category, muscle, equipment, instructions, is_custom, is_active, created_at) SELECT gen_random_uuid(), 'Peck Deck', 'Peito', 'Peitoral', 'Máquina', 'Sente na máquina peck deck com as costas apoiadas e os cotovelos sobre as almofadas. Traga os braços para frente e para o centro, contraindo o peitoral ao final. Retorne controlado sem deixar os cotovelos irem além da linha do corpo. Excelente para isolamento do peitoral.', false, true, NOW() WHERE NOT EXISTS (SELECT 1 FROM exercise_catalog WHERE name = 'Peck Deck' AND category = 'Peito' AND is_custom = false);

INSERT INTO exercise_catalog (id, name, category, muscle, equipment, instructions, is_custom, is_active, created_at) SELECT gen_random_uuid(), 'Press de Peito na Máquina', 'Peito', 'Peitoral', 'Máquina', 'Ajuste o assento para que as alças fiquem na altura do peito médio. Empurre as alças para frente estendendo os braços, contraindo o peitoral. Retorne controlado sem bater os pesos. Permite carga segura sem necessidade de spotter.', false, true, NOW() WHERE NOT EXISTS (SELECT 1 FROM exercise_catalog WHERE name = 'Press de Peito na Máquina' AND category = 'Peito' AND is_custom = false);

INSERT INTO exercise_catalog (id, name, category, muscle, equipment, instructions, is_custom, is_active, created_at) SELECT gen_random_uuid(), 'Flexão de Braço', 'Peito', 'Peitoral', 'Peso corporal', 'Apoie as mãos no chão um pouco mais largas que os ombros e os pés esticados, formando uma linha reta com o corpo. Desça o peito em direção ao chão flexionando os cotovelos. Empurre de volta contraindo o peitoral. Variações mais largas enfatizam o peitoral, pegada estreita enfatiza o tríceps.', false, true, NOW() WHERE NOT EXISTS (SELECT 1 FROM exercise_catalog WHERE name = 'Flexão de Braço' AND category = 'Peito' AND is_custom = false);

INSERT INTO exercise_catalog (id, name, category, muscle, equipment, instructions, is_custom, is_active, created_at) SELECT gen_random_uuid(), 'Paralelas com Foco em Peito', 'Peito', 'Peitoral', 'Paralelas', 'Segure as barras paralelas com os braços estendidos. Incline o tronco levemente para frente durante o movimento. Desça flexionando os cotovelos até sentir alongamento no peitoral e suba. Evite subir completamente para manter a tensão no músculo. Trabalha peitoral inferior e tríceps.', false, true, NOW() WHERE NOT EXISTS (SELECT 1 FROM exercise_catalog WHERE name = 'Paralelas com Foco em Peito' AND category = 'Peito' AND is_custom = false);

-- COSTAS E DORSAIS
INSERT INTO exercise_catalog (id, name, category, muscle, equipment, instructions, is_custom, is_active, created_at) SELECT gen_random_uuid(), 'Puxada Frente na Polia', 'Costas e Dorsais', 'Dorsal', 'Polia', 'Sente na máquina de puxada com as coxas presas sob o suporte. Segure a barra com pegada pronada, mais larga que os ombros. Incline levemente o tronco para trás e puxe a barra até a altura do queixo, retraindo as escápulas. Suba controlado sem soltar as escápulas abruptamente.', false, true, NOW() WHERE NOT EXISTS (SELECT 1 FROM exercise_catalog WHERE name = 'Puxada Frente na Polia' AND category = 'Costas e Dorsais' AND is_custom = false);

INSERT INTO exercise_catalog (id, name, category, muscle, equipment, instructions, is_custom, is_active, created_at) SELECT gen_random_uuid(), 'Barra Fixa', 'Costas e Dorsais', 'Dorsal', 'Barra fixa', 'Segure a barra fixa com pegada pronada, mais larga que os ombros. A partir da posição com braços estendidos, puxe o corpo para cima até o queixo ultrapassar a barra. Contraia o dorsal no topo e desça de forma controlada. Mantenha o core ativo e evite balanços.', false, true, NOW() WHERE NOT EXISTS (SELECT 1 FROM exercise_catalog WHERE name = 'Barra Fixa' AND category = 'Costas e Dorsais' AND is_custom = false);

INSERT INTO exercise_catalog (id, name, category, muscle, equipment, instructions, is_custom, is_active, created_at) SELECT gen_random_uuid(), 'Remada Curvada', 'Costas e Dorsais', 'Dorsal', 'Barra', 'Segure a barra com pegada pronada, afastada na largura dos ombros. Incline o tronco a 45 graus mantendo a lombar neutra. Puxe a barra em direção ao umbigo retraindo as escápulas ao final. Estenda os braços controlado. Trabalha todo o complexo muscular das costas.', false, true, NOW() WHERE NOT EXISTS (SELECT 1 FROM exercise_catalog WHERE name = 'Remada Curvada' AND category = 'Costas e Dorsais' AND is_custom = false);

INSERT INTO exercise_catalog (id, name, category, muscle, equipment, instructions, is_custom, is_active, created_at) SELECT gen_random_uuid(), 'Remada Baixa na Polia', 'Costas e Dorsais', 'Dorsal', 'Polia', 'Sente no banco da remada baixa com os pés no apoio e os joelhos levemente flexionados. Segure o triângulo e puxe em direção ao abdômen, retraindo as escápulas ao final. Estenda os braços completamente antes da próxima repetição. Mantenha o tronco ereto.', false, true, NOW() WHERE NOT EXISTS (SELECT 1 FROM exercise_catalog WHERE name = 'Remada Baixa na Polia' AND category = 'Costas e Dorsais' AND is_custom = false);

INSERT INTO exercise_catalog (id, name, category, muscle, equipment, instructions, is_custom, is_active, created_at) SELECT gen_random_uuid(), 'Remada Cavalinho', 'Costas e Dorsais', 'Dorsal', 'Máquina', 'Apoie o peito no suporte almofadado da máquina. Segure as alças com os braços estendidos e puxe em direção ao corpo, retraindo as escápulas ao final do movimento. Retorne controlado sem soltar as escápulas. Exercício seguro que isola bem o dorsal.', false, true, NOW() WHERE NOT EXISTS (SELECT 1 FROM exercise_catalog WHERE name = 'Remada Cavalinho' AND category = 'Costas e Dorsais' AND is_custom = false);

INSERT INTO exercise_catalog (id, name, category, muscle, equipment, instructions, is_custom, is_active, created_at) SELECT gen_random_uuid(), 'Remada Unilateral com Halter', 'Costas e Dorsais', 'Dorsal', 'Halter', 'Apoie o joelho e a mão do mesmo lado no banco para suporte. Com o outro braço, segure o halter com o braço estendido. Puxe o halter em direção ao quadril retraindo a escápula. Desça controlado e repita. Permite maior amplitude de movimento e correção de desequilíbrios.', false, true, NOW() WHERE NOT EXISTS (SELECT 1 FROM exercise_catalog WHERE name = 'Remada Unilateral com Halter' AND category = 'Costas e Dorsais' AND is_custom = false);

INSERT INTO exercise_catalog (id, name, category, muscle, equipment, instructions, is_custom, is_active, created_at) SELECT gen_random_uuid(), 'Puxada com Pegada Supinada', 'Costas e Dorsais', 'Dorsal', 'Polia', 'Sente na máquina de puxada e segure a barra com pegada supinada na largura dos ombros. Puxe a barra até a altura do queixo ou do peito, retraindo as escápulas. A pegada supinada recruta mais o bíceps e aumenta a amplitude do dorsal.', false, true, NOW() WHERE NOT EXISTS (SELECT 1 FROM exercise_catalog WHERE name = 'Puxada com Pegada Supinada' AND category = 'Costas e Dorsais' AND is_custom = false);

INSERT INTO exercise_catalog (id, name, category, muscle, equipment, instructions, is_custom, is_active, created_at) SELECT gen_random_uuid(), 'Pullover na Polia Alta', 'Costas e Dorsais', 'Dorsal', 'Polia', 'Fique de frente para a polia alta, ligeiramente inclinado. Segure a barra ou corda com os braços estendidos acima. Puxe os braços em arco descendente até ficarem ao lado do corpo, contraindo o dorsal. Retorne controlado. Trabalha o dorsal em amplitude total sem envolvimento do bíceps.', false, true, NOW() WHERE NOT EXISTS (SELECT 1 FROM exercise_catalog WHERE name = 'Pullover na Polia Alta' AND category = 'Costas e Dorsais' AND is_custom = false);

INSERT INTO exercise_catalog (id, name, category, muscle, equipment, instructions, is_custom, is_active, created_at) SELECT gen_random_uuid(), 'Remada Articulada na Máquina', 'Costas e Dorsais', 'Dorsal', 'Máquina', 'Ajuste o assento para que as alças fiquem na altura dos ombros. Segure as alças e puxe em direção ao peito ou abdômen, retraindo as escápulas ao final. Retorne controlado. A máquina articulada permite isolar os músculos das costas com segurança.', false, true, NOW() WHERE NOT EXISTS (SELECT 1 FROM exercise_catalog WHERE name = 'Remada Articulada na Máquina' AND category = 'Costas e Dorsais' AND is_custom = false);

INSERT INTO exercise_catalog (id, name, category, muscle, equipment, instructions, is_custom, is_active, created_at) SELECT gen_random_uuid(), 'Crucifixo Invertido no Banco Inclinado', 'Costas e Dorsais', 'Dorsal', 'Halteres', 'Ajuste o banco inclinado a 30-45 graus e deite de bruços. Segure os halteres com os braços pendurados abaixo. Eleve os braços lateralmente até a altura dos ombros, contraindo as escápulas. Retorne controlado. Trabalha o romboide, trapézio médio e deltoides posterior.', false, true, NOW() WHERE NOT EXISTS (SELECT 1 FROM exercise_catalog WHERE name = 'Crucifixo Invertido no Banco Inclinado' AND category = 'Costas e Dorsais' AND is_custom = false);

-- LOMBAR
INSERT INTO exercise_catalog (id, name, category, muscle, equipment, instructions, is_custom, is_active, created_at) SELECT gen_random_uuid(), 'Levantamento Terra', 'Lombar', 'Lombar', 'Barra', 'Com a barra no chão, posicione os pés na largura do quadril e segure a barra com pegada pronada ou alternada. Mantenha a lombar neutra, o peito alto e os ombros afastados do corpo. Suba estendendo quadril e joelhos simultaneamente. Desça controlado. Um dos exercícios mais completos do treino.', false, true, NOW() WHERE NOT EXISTS (SELECT 1 FROM exercise_catalog WHERE name = 'Levantamento Terra' AND category = 'Lombar' AND is_custom = false);

INSERT INTO exercise_catalog (id, name, category, muscle, equipment, instructions, is_custom, is_active, created_at) SELECT gen_random_uuid(), 'Hiperextensão Lombar', 'Lombar', 'Lombar', 'Banco romano', 'Posicione os quadris na borda do banco romano com os calcanhares presos no suporte. Com as mãos atrás da cabeça ou cruzadas no peito, incline o tronco para baixo e suba até a posição neutra da coluna. Não hipere...estenda demais para proteger a lombar.', false, true, NOW() WHERE NOT EXISTS (SELECT 1 FROM exercise_catalog WHERE name = 'Hiperextensão Lombar' AND category = 'Lombar' AND is_custom = false);

INSERT INTO exercise_catalog (id, name, category, muscle, equipment, instructions, is_custom, is_active, created_at) SELECT gen_random_uuid(), 'Bom Dia', 'Lombar', 'Lombar', 'Barra', 'Apoie a barra nos ombros como no agachamento. Com os joelhos levemente flexionados, incline o tronco para frente mantendo a lombar neutra até sentir o alongamento nos posteriores. Volte à posição inicial contraindo a lombar e os glúteos.', false, true, NOW() WHERE NOT EXISTS (SELECT 1 FROM exercise_catalog WHERE name = 'Bom Dia' AND category = 'Lombar' AND is_custom = false);

INSERT INTO exercise_catalog (id, name, category, muscle, equipment, instructions, is_custom, is_active, created_at) SELECT gen_random_uuid(), 'Super-homem', 'Lombar', 'Lombar', 'Peso corporal', 'Deite de bruços com os braços estendidos acima da cabeça. Eleve simultaneamente braços e pernas do chão, contraindo a lombar e glúteos. Segure por 2-3 segundos no topo e desça controlado. Exercício isométrico eficaz para fortalecer a cadeia posterior.', false, true, NOW() WHERE NOT EXISTS (SELECT 1 FROM exercise_catalog WHERE name = 'Super-homem' AND category = 'Lombar' AND is_custom = false);

INSERT INTO exercise_catalog (id, name, category, muscle, equipment, instructions, is_custom, is_active, created_at) SELECT gen_random_uuid(), 'Prancha Ventral', 'Lombar', 'Lombar', 'Peso corporal', 'Apoie os antebraços e as pontas dos pés no chão. Mantenha o corpo em linha reta da cabeça aos calcanhares. Contraia o abdômen, glúteos e mantenha o quadril nivelado. Segure a posição pelo tempo determinado. Trabalha isometricamente toda a cadeia estabilizadora.', false, true, NOW() WHERE NOT EXISTS (SELECT 1 FROM exercise_catalog WHERE name = 'Prancha Ventral' AND category = 'Lombar' AND is_custom = false);

INSERT INTO exercise_catalog (id, name, category, muscle, equipment, instructions, is_custom, is_active, created_at) SELECT gen_random_uuid(), 'Levantamento Terra Romeno', 'Lombar', 'Lombar', 'Barra', 'Segure a barra na frente das coxas com pegada pronada. Com os joelhos levemente flexionados e fixos, incline o tronco para frente deslizando a barra pela perna até sentir o alongamento nos posteriores. Volte contraindo a lombar e glúteos. Foco no posterior e lombar.', false, true, NOW() WHERE NOT EXISTS (SELECT 1 FROM exercise_catalog WHERE name = 'Levantamento Terra Romeno' AND category = 'Lombar' AND is_custom = false);

INSERT INTO exercise_catalog (id, name, category, muscle, equipment, instructions, is_custom, is_active, created_at) SELECT gen_random_uuid(), 'Perdigueiro', 'Lombar', 'Lombar', 'Peso corporal', 'A partir da posição de quatro apoios, estenda simultaneamente o braço direito para frente e a perna esquerda para trás. Segure 2-3 segundos e alterne os lados. Mantém o core estável e a lombar neutra durante o movimento. Excelente para reabilitação e estabilidade lombar.', false, true, NOW() WHERE NOT EXISTS (SELECT 1 FROM exercise_catalog WHERE name = 'Perdigueiro' AND category = 'Lombar' AND is_custom = false);

INSERT INTO exercise_catalog (id, name, category, muscle, equipment, instructions, is_custom, is_active, created_at) SELECT gen_random_uuid(), 'Hiperextensão Lombar no Chão', 'Lombar', 'Lombar', 'Peso corporal', 'Deite de bruços com as mãos atrás da cabeça. Eleve apenas o tronco do chão contraindo a lombar, sem elevar demais. Segure 1-2 segundos no topo e desça. Variação acessível da hiperextensão para iniciantes ou treinos sem banco romano.', false, true, NOW() WHERE NOT EXISTS (SELECT 1 FROM exercise_catalog WHERE name = 'Hiperextensão Lombar no Chão' AND category = 'Lombar' AND is_custom = false);

INSERT INTO exercise_catalog (id, name, category, muscle, equipment, instructions, is_custom, is_active, created_at) SELECT gen_random_uuid(), 'Ponte de Glúteos', 'Lombar', 'Lombar', 'Peso corporal', 'Deite de costas com os joelhos flexionados e pés apoiados no chão. Eleve o quadril contraindo os glúteos e a lombar até formar uma linha reta entre joelhos e ombros. Segure 2 segundos no topo e desça controlado. Fortalece lombar, glúteos e isquiotibiais.', false, true, NOW() WHERE NOT EXISTS (SELECT 1 FROM exercise_catalog WHERE name = 'Ponte de Glúteos' AND category = 'Lombar' AND is_custom = false);

INSERT INTO exercise_catalog (id, name, category, muscle, equipment, instructions, is_custom, is_active, created_at) SELECT gen_random_uuid(), 'Prancha Lateral', 'Lombar', 'Lombar', 'Peso corporal', 'Apoie o antebraço lateral e os pés (um sobre o outro) no chão. Eleve o quadril formando uma linha reta com o corpo. Contraia o core e segure a posição pelo tempo determinado. Repita dos dois lados. Trabalha o quadrado lombar e oblíquos.', false, true, NOW() WHERE NOT EXISTS (SELECT 1 FROM exercise_catalog WHERE name = 'Prancha Lateral' AND category = 'Lombar' AND is_custom = false);

-- OMBROS
INSERT INTO exercise_catalog (id, name, category, muscle, equipment, instructions, is_custom, is_active, created_at) SELECT gen_random_uuid(), 'Desenvolvimento com Halteres', 'Ombros', 'Deltoides', 'Halteres', 'Sente em um banco com encosto reto, segure os halteres na altura dos ombros com as palmas voltadas para frente. Empurre os halteres para cima até os braços quase estendidos e desça controlado. Trabalha o deltoides anterior e médio com menos carga no pescoço que o desenvolvimento militar.', false, true, NOW() WHERE NOT EXISTS (SELECT 1 FROM exercise_catalog WHERE name = 'Desenvolvimento com Halteres' AND category = 'Ombros' AND is_custom = false);

INSERT INTO exercise_catalog (id, name, category, muscle, equipment, instructions, is_custom, is_active, created_at) SELECT gen_random_uuid(), 'Desenvolvimento Militar', 'Ombros', 'Deltoides', 'Barra', 'Fique em pé ou sente, segure a barra com pegada pronada na largura dos ombros na frente do peito. Empurre a barra acima da cabeça até os braços quase estendidos e desça controlado. Exercício composto para deltoides anterior e médio com boa sobrecarga.', false, true, NOW() WHERE NOT EXISTS (SELECT 1 FROM exercise_catalog WHERE name = 'Desenvolvimento Militar' AND category = 'Ombros' AND is_custom = false);

INSERT INTO exercise_catalog (id, name, category, muscle, equipment, instructions, is_custom, is_active, created_at) SELECT gen_random_uuid(), 'Elevação Lateral com Halteres', 'Ombros', 'Deltoides', 'Halteres', 'Fique em pé com os halteres ao lado do corpo. Com cotovelos levemente flexionados, eleve os braços lateralmente até a altura dos ombros. Desça controlado. Isola o deltoides médio. Use cargas moderadas e evite balançar o tronco.', false, true, NOW() WHERE NOT EXISTS (SELECT 1 FROM exercise_catalog WHERE name = 'Elevação Lateral com Halteres' AND category = 'Ombros' AND is_custom = false);

INSERT INTO exercise_catalog (id, name, category, muscle, equipment, instructions, is_custom, is_active, created_at) SELECT gen_random_uuid(), 'Elevação Lateral no Cabo', 'Ombros', 'Deltoides', 'Polia', 'Fique ao lado da polia baixa e segure a alça com a mão distante. Eleve o braço lateralmente até a altura do ombro e desça controlado. O cabo mantém tensão constante em toda a amplitude, diferente do halter. Execute dos dois lados.', false, true, NOW() WHERE NOT EXISTS (SELECT 1 FROM exercise_catalog WHERE name = 'Elevação Lateral no Cabo' AND category = 'Ombros' AND is_custom = false);

INSERT INTO exercise_catalog (id, name, category, muscle, equipment, instructions, is_custom, is_active, created_at) SELECT gen_random_uuid(), 'Elevação Frontal', 'Ombros', 'Deltoides', 'Halteres', 'Fique em pé com os halteres na frente das coxas, palmas voltadas para o corpo. Eleve um ou ambos os braços para frente até a altura dos ombros e desça controlado. Trabalha o deltoides anterior. Evite balançar o tronco para compensar o movimento.', false, true, NOW() WHERE NOT EXISTS (SELECT 1 FROM exercise_catalog WHERE name = 'Elevação Frontal' AND category = 'Ombros' AND is_custom = false);

INSERT INTO exercise_catalog (id, name, category, muscle, equipment, instructions, is_custom, is_active, created_at) SELECT gen_random_uuid(), 'Crucifixo Invertido com Halteres', 'Ombros', 'Deltoides', 'Halteres', 'Incline o tronco à frente a 45-90 graus, segure os halteres com os braços abaixo. Eleve os braços lateralmente até a altura dos ombros contraindo o deltoides posterior e as escápulas. Desça controlado. Trabalha deltoides posterior e romboides.', false, true, NOW() WHERE NOT EXISTS (SELECT 1 FROM exercise_catalog WHERE name = 'Crucifixo Invertido com Halteres' AND category = 'Ombros' AND is_custom = false);

INSERT INTO exercise_catalog (id, name, category, muscle, equipment, instructions, is_custom, is_active, created_at) SELECT gen_random_uuid(), 'Voador Inverso', 'Ombros', 'Deltoides', 'Máquina', 'Ajuste a máquina de voador para o modo inverso (pec deck invertido). Segure as alças e puxe os braços para trás e para os lados, contraindo o deltoides posterior. Retorne controlado. Excelente para correção postural e fortalecimento do deltoides posterior.', false, true, NOW() WHERE NOT EXISTS (SELECT 1 FROM exercise_catalog WHERE name = 'Voador Inverso' AND category = 'Ombros' AND is_custom = false);

INSERT INTO exercise_catalog (id, name, category, muscle, equipment, instructions, is_custom, is_active, created_at) SELECT gen_random_uuid(), 'Elevação Frontal na Polia Baixa', 'Ombros', 'Deltoides', 'Polia', 'Fique de frente para a polia baixa e segure a alça ou barra. Com o braço quase estendido, eleve para frente até a altura dos ombros. O cabo mantém tensão constante no deltoides anterior durante todo o movimento. Desça controlado.', false, true, NOW() WHERE NOT EXISTS (SELECT 1 FROM exercise_catalog WHERE name = 'Elevação Frontal na Polia Baixa' AND category = 'Ombros' AND is_custom = false);

INSERT INTO exercise_catalog (id, name, category, muscle, equipment, instructions, is_custom, is_active, created_at) SELECT gen_random_uuid(), 'Remada Alta', 'Ombros', 'Deltoides', 'Barra', 'Segure a barra com pegada pronada estreita. Puxe a barra verticalmente até a altura do queixo, mantendo os cotovelos acima dos punhos. Desça controlado. Trabalha deltoides médio e trapézio. Cuidado com cargas excessivas para evitar impacto nos ombros.', false, true, NOW() WHERE NOT EXISTS (SELECT 1 FROM exercise_catalog WHERE name = 'Remada Alta' AND category = 'Ombros' AND is_custom = false);

INSERT INTO exercise_catalog (id, name, category, muscle, equipment, instructions, is_custom, is_active, created_at) SELECT gen_random_uuid(), 'Face Pull', 'Ombros', 'Deltoides', 'Polia', 'Posicione a polia na altura dos olhos com corda. Puxe a corda em direção ao rosto separando as pontas na chegada, mantendo os cotovelos elevados. Contraia o deltoides posterior e retratores escapulares. Excelente para saúde dos ombros e postura.', false, true, NOW() WHERE NOT EXISTS (SELECT 1 FROM exercise_catalog WHERE name = 'Face Pull' AND category = 'Ombros' AND is_custom = false);

-- BÍCEPS
INSERT INTO exercise_catalog (id, name, category, muscle, equipment, instructions, is_custom, is_active, created_at) SELECT gen_random_uuid(), 'Rosca Direta com Barra', 'Bíceps', 'Bíceps', 'Barra', 'Fique em pé, segure a barra com pegada supinada na largura dos ombros. Mantendo os cotovelos fixos ao lado do corpo, flexione os cotovelos trazendo a barra até os ombros. Contraia no topo e desça controlado. Principal exercício para volume do bíceps.', false, true, NOW() WHERE NOT EXISTS (SELECT 1 FROM exercise_catalog WHERE name = 'Rosca Direta com Barra' AND category = 'Bíceps' AND is_custom = false);

INSERT INTO exercise_catalog (id, name, category, muscle, equipment, instructions, is_custom, is_active, created_at) SELECT gen_random_uuid(), 'Rosca Alternada com Halteres', 'Bíceps', 'Bíceps', 'Halteres', 'Fique em pé com os halteres ao lado do corpo. Flexione um cotovelo de cada vez, supinando o punho ao subir. Desça controlado e alterne os lados. A alternância permite foco em cada braço e a supinação aumenta a contração do bíceps.', false, true, NOW() WHERE NOT EXISTS (SELECT 1 FROM exercise_catalog WHERE name = 'Rosca Alternada com Halteres' AND category = 'Bíceps' AND is_custom = false);

INSERT INTO exercise_catalog (id, name, category, muscle, equipment, instructions, is_custom, is_active, created_at) SELECT gen_random_uuid(), 'Rosca Scott', 'Bíceps', 'Bíceps', 'Barra e banco Scott', 'Apoie a parte posterior dos braços no suporte inclinado do banco Scott. Segure a barra EZ ou reta com pegada supinada e flexione os cotovelos completamente. Desça controlado sem soltar os braços do suporte. Isola o bíceps eliminando o movimento do tronco.', false, true, NOW() WHERE NOT EXISTS (SELECT 1 FROM exercise_catalog WHERE name = 'Rosca Scott' AND category = 'Bíceps' AND is_custom = false);

INSERT INTO exercise_catalog (id, name, category, muscle, equipment, instructions, is_custom, is_active, created_at) SELECT gen_random_uuid(), 'Rosca Martelo com Halteres', 'Bíceps', 'Bíceps', 'Halteres', 'Fique em pé com os halteres ao lado do corpo, palmas voltadas para dentro (pegada neutra). Flexione os cotovelos mantendo as palmas na posição neutra durante todo o movimento. Desce controlado. Trabalha bíceps braquial e braquiorradial com ênfase diferente da rosca supinada.', false, true, NOW() WHERE NOT EXISTS (SELECT 1 FROM exercise_catalog WHERE name = 'Rosca Martelo com Halteres' AND category = 'Bíceps' AND is_custom = false);

INSERT INTO exercise_catalog (id, name, category, muscle, equipment, instructions, is_custom, is_active, created_at) SELECT gen_random_uuid(), 'Rosca Inclinada com Halteres', 'Bíceps', 'Bíceps', 'Halteres', 'Recline o banco a 45-60 graus e sente com os halteres pendentes ao lado do corpo. Flexione os cotovelos trazendo os halteres até os ombros, supinando ao subir. A posição inclinada aumenta o alongamento inicial do bíceps, gerando maior tensão.', false, true, NOW() WHERE NOT EXISTS (SELECT 1 FROM exercise_catalog WHERE name = 'Rosca Inclinada com Halteres' AND category = 'Bíceps' AND is_custom = false);

INSERT INTO exercise_catalog (id, name, category, muscle, equipment, instructions, is_custom, is_active, created_at) SELECT gen_random_uuid(), 'Rosca Concentrada', 'Bíceps', 'Bíceps', 'Halter', 'Sente em um banco, apoie o cotovelo do braço que irá trabalhar na face interna da coxa. Segure o halter e flexione o cotovelo completamente, contraindo o bíceps. Desça controlado. Permite foco total em um braço de cada vez com alto grau de isolamento.', false, true, NOW() WHERE NOT EXISTS (SELECT 1 FROM exercise_catalog WHERE name = 'Rosca Concentrada' AND category = 'Bíceps' AND is_custom = false);

INSERT INTO exercise_catalog (id, name, category, muscle, equipment, instructions, is_custom, is_active, created_at) SELECT gen_random_uuid(), 'Rosca Direta no Cabo', 'Bíceps', 'Bíceps', 'Polia', 'Posicione a polia baixa e segure a barra reta ou EZ. Mantendo os cotovelos fixos, flexione trazendo a barra até os ombros. O cabo mantém tensão constante durante todo o movimento, diferente da barra livre. Desça controlado.', false, true, NOW() WHERE NOT EXISTS (SELECT 1 FROM exercise_catalog WHERE name = 'Rosca Direta no Cabo' AND category = 'Bíceps' AND is_custom = false);

INSERT INTO exercise_catalog (id, name, category, muscle, equipment, instructions, is_custom, is_active, created_at) SELECT gen_random_uuid(), 'Rosca Martelo com Corda na Polia', 'Bíceps', 'Bíceps', 'Polia', 'Posicione a polia baixa com corda. Segure com pegada neutra e flexione os cotovelos mantendo as palmas voltadas para dentro. A tensão do cabo garante resistência constante. Trabalha o braquiorradial e bíceps com foco na pegada neutra.', false, true, NOW() WHERE NOT EXISTS (SELECT 1 FROM exercise_catalog WHERE name = 'Rosca Martelo com Corda na Polia' AND category = 'Bíceps' AND is_custom = false);

INSERT INTO exercise_catalog (id, name, category, muscle, equipment, instructions, is_custom, is_active, created_at) SELECT gen_random_uuid(), 'Rosca Spider', 'Bíceps', 'Bíceps', 'Barra', 'Deite de bruços em um banco inclinado a 45 graus. Segure a barra reta com pegada supinada. Flexione os cotovelos sem mover os braços para trás, contraindo o bíceps no topo. Desça controlado. Elimina o movimento de ombros e isola muito bem o pico do bíceps.', false, true, NOW() WHERE NOT EXISTS (SELECT 1 FROM exercise_catalog WHERE name = 'Rosca Spider' AND category = 'Bíceps' AND is_custom = false);

INSERT INTO exercise_catalog (id, name, category, muscle, equipment, instructions, is_custom, is_active, created_at) SELECT gen_random_uuid(), 'Rosca 21', 'Bíceps', 'Bíceps', 'Barra', 'Execute 7 repetições na metade inferior (do início até 90 graus), depois 7 na metade superior (de 90 graus até o topo), depois 7 completas. Total de 21 repetições em uma série. Técnica de choque que trabalha diferentes partes da curva de força do bíceps.', false, true, NOW() WHERE NOT EXISTS (SELECT 1 FROM exercise_catalog WHERE name = 'Rosca 21' AND category = 'Bíceps' AND is_custom = false);

-- TRÍCEPS
INSERT INTO exercise_catalog (id, name, category, muscle, equipment, instructions, is_custom, is_active, created_at) SELECT gen_random_uuid(), 'Tríceps Pulley', 'Tríceps', 'Tríceps', 'Polia', 'Posicione a polia alta com barra reta. Segure com pegada pronada na largura dos ombros e mantenha os cotovelos fixos ao lado do corpo. Empurre a barra para baixo estendendo os braços completamente. Contraia o tríceps no final e retorne controlado. Exercício básico para volume do tríceps.', false, true, NOW() WHERE NOT EXISTS (SELECT 1 FROM exercise_catalog WHERE name = 'Tríceps Pulley' AND category = 'Tríceps' AND is_custom = false);

INSERT INTO exercise_catalog (id, name, category, muscle, equipment, instructions, is_custom, is_active, created_at) SELECT gen_random_uuid(), 'Tríceps Corda', 'Tríceps', 'Tríceps', 'Polia', 'Posicione a polia alta com corda. Segure as pontas da corda com pegada neutra. Empurre para baixo separando as pontas ao final para maximizar a contração do tríceps. Mantenha os cotovelos fixos ao lado do corpo durante o movimento.', false, true, NOW() WHERE NOT EXISTS (SELECT 1 FROM exercise_catalog WHERE name = 'Tríceps Corda' AND category = 'Tríceps' AND is_custom = false);

INSERT INTO exercise_catalog (id, name, category, muscle, equipment, instructions, is_custom, is_active, created_at) SELECT gen_random_uuid(), 'Tríceps Testa', 'Tríceps', 'Tríceps', 'Barra', 'Deite no banco plano e segure a barra EZ ou reta acima do peito com pegada pronada. Mantenha os cotovelos apontados para cima e dobre os braços trazendo a barra em direção à testa. Estenda os braços de volta. Trabalha especialmente a cabeça longa do tríceps.', false, true, NOW() WHERE NOT EXISTS (SELECT 1 FROM exercise_catalog WHERE name = 'Tríceps Testa' AND category = 'Tríceps' AND is_custom = false);

INSERT INTO exercise_catalog (id, name, category, muscle, equipment, instructions, is_custom, is_active, created_at) SELECT gen_random_uuid(), 'Tríceps Francês', 'Tríceps', 'Tríceps', 'Halteres', 'Sente ou fique em pé. Segure o halter ou barra EZ acima da cabeça com os braços estendidos. Flexione os cotovelos abaixando a carga atrás da cabeça. Estenda de volta. Trabalha a cabeça longa do tríceps em posição de alongamento máximo.', false, true, NOW() WHERE NOT EXISTS (SELECT 1 FROM exercise_catalog WHERE name = 'Tríceps Francês' AND category = 'Tríceps' AND is_custom = false);

INSERT INTO exercise_catalog (id, name, category, muscle, equipment, instructions, is_custom, is_active, created_at) SELECT gen_random_uuid(), 'Supino Fechado', 'Tríceps', 'Tríceps', 'Barra', 'Deite no banco plano e segure a barra com pegada mais estreita que os ombros. Desça a barra em direção ao peito inferior mantendo os cotovelos próximos ao corpo. Empurre de volta contraindo o tríceps. Exercício composto que também envolve peitoral e deltoides anterior.', false, true, NOW() WHERE NOT EXISTS (SELECT 1 FROM exercise_catalog WHERE name = 'Supino Fechado' AND category = 'Tríceps' AND is_custom = false);

INSERT INTO exercise_catalog (id, name, category, muscle, equipment, instructions, is_custom, is_active, created_at) SELECT gen_random_uuid(), 'Mergulho nas Paralelas', 'Tríceps', 'Tríceps', 'Paralelas', 'Segure as barras paralelas com os braços estendidos e o tronco ereto. Desça flexionando os cotovelos mantendo o tronco vertical para focar no tríceps. Suba até quase estender os cotovelos. Com inclinação do tronco, aumenta o trabalho do peitoral.', false, true, NOW() WHERE NOT EXISTS (SELECT 1 FROM exercise_catalog WHERE name = 'Mergulho nas Paralelas' AND category = 'Tríceps' AND is_custom = false);

INSERT INTO exercise_catalog (id, name, category, muscle, equipment, instructions, is_custom, is_active, created_at) SELECT gen_random_uuid(), 'Tríceps Banco', 'Tríceps', 'Tríceps', 'Banco', 'Apoie as mãos em um banco atrás do corpo com os pés estendidos à frente. Desça o quadril flexionando os cotovelos até ângulo de 90 graus. Empurre de volta. Para aumentar a dificuldade, eleve os pés em outro banco. Exercício de peso corporal para o tríceps.', false, true, NOW() WHERE NOT EXISTS (SELECT 1 FROM exercise_catalog WHERE name = 'Tríceps Banco' AND category = 'Tríceps' AND is_custom = false);

INSERT INTO exercise_catalog (id, name, category, muscle, equipment, instructions, is_custom, is_active, created_at) SELECT gen_random_uuid(), 'Tríceps Coice', 'Tríceps', 'Tríceps', 'Halter', 'Apoie o joelho e mão no banco. Com o outro braço, segure o halter e leve o braço ao lado do corpo com o cotovelo a 90 graus. Estenda o braço para trás contraindo o tríceps. Desça controlado. Isola bem o tríceps e trabalha a cabeça lateral.', false, true, NOW() WHERE NOT EXISTS (SELECT 1 FROM exercise_catalog WHERE name = 'Tríceps Coice' AND category = 'Tríceps' AND is_custom = false);

INSERT INTO exercise_catalog (id, name, category, muscle, equipment, instructions, is_custom, is_active, created_at) SELECT gen_random_uuid(), 'Tríceps Francês Unilateral', 'Tríceps', 'Tríceps', 'Halter', 'Fique em pé ou sente. Segure o halter com uma mão acima da cabeça com o braço estendido. Flexione o cotovelo abaixando o halter atrás da cabeça. Estenda de volta. Execute dos dois lados. Permite identificar e corrigir desequilíbrios entre os braços.', false, true, NOW() WHERE NOT EXISTS (SELECT 1 FROM exercise_catalog WHERE name = 'Tríceps Francês Unilateral' AND category = 'Tríceps' AND is_custom = false);

INSERT INTO exercise_catalog (id, name, category, muscle, equipment, instructions, is_custom, is_active, created_at) SELECT gen_random_uuid(), 'Tríceps Invertido no Pulley', 'Tríceps', 'Tríceps', 'Polia', 'Posicione a polia alta com barra reta. Segure com pegada supinada (palmas para cima). Mantenha os cotovelos fixos ao lado do corpo e empurre para baixo estendendo os braços. Retorne controlado. A pegada supinada varia o estímulo no tríceps.', false, true, NOW() WHERE NOT EXISTS (SELECT 1 FROM exercise_catalog WHERE name = 'Tríceps Invertido no Pulley' AND category = 'Tríceps' AND is_custom = false);

-- ANTEBRAÇO
INSERT INTO exercise_catalog (id, name, category, muscle, equipment, instructions, is_custom, is_active, created_at) SELECT gen_random_uuid(), 'Rosca Inversa', 'Antebraço', 'Antebraço', 'Barra', 'Segure a barra com pegada pronada (palmas para baixo) na largura dos ombros. Flexione os cotovelos como na rosca direta, mantendo a pegada pronada. Desça controlado. Trabalha o extensor do punho e braquiorradial, complementando a rosca supinada.', false, true, NOW() WHERE NOT EXISTS (SELECT 1 FROM exercise_catalog WHERE name = 'Rosca Inversa' AND category = 'Antebraço' AND is_custom = false);

INSERT INTO exercise_catalog (id, name, category, muscle, equipment, instructions, is_custom, is_active, created_at) SELECT gen_random_uuid(), 'Rosca Pulso', 'Antebraço', 'Antebraço', 'Barra', 'Sente em um banco e apoie os antebraços nas coxas com os punhos para fora da borda. Segure a barra com pegada supinada e flexione os punhos para cima. Desça controlado. Trabalha os flexores do punho e fortalece a pegada.', false, true, NOW() WHERE NOT EXISTS (SELECT 1 FROM exercise_catalog WHERE name = 'Rosca Pulso' AND category = 'Antebraço' AND is_custom = false);

INSERT INTO exercise_catalog (id, name, category, muscle, equipment, instructions, is_custom, is_active, created_at) SELECT gen_random_uuid(), 'Rosca Pulso Inversa', 'Antebraço', 'Antebraço', 'Barra', 'Sente em um banco, apoie os antebraços nas coxas com os punhos para fora da borda. Segure a barra com pegada pronada e estenda os punhos para cima. Desça controlado. Trabalha os extensores do punho, complementando a rosca de punho.', false, true, NOW() WHERE NOT EXISTS (SELECT 1 FROM exercise_catalog WHERE name = 'Rosca Pulso Inversa' AND category = 'Antebraço' AND is_custom = false);

INSERT INTO exercise_catalog (id, name, category, muscle, equipment, instructions, is_custom, is_active, created_at) SELECT gen_random_uuid(), 'Caminhada do Fazendeiro', 'Antebraço', 'Antebraço', 'Halteres', 'Segure halteres pesados em cada mão ao lado do corpo. Caminhe por uma distância determinada mantendo a postura ereta. Desenvolve a força de preensão, antebraços e estabilidade do core. Um dos melhores exercícios funcionais para a pegada.', false, true, NOW() WHERE NOT EXISTS (SELECT 1 FROM exercise_catalog WHERE name = 'Caminhada do Fazendeiro' AND category = 'Antebraço' AND is_custom = false);

INSERT INTO exercise_catalog (id, name, category, muscle, equipment, instructions, is_custom, is_active, created_at) SELECT gen_random_uuid(), 'Giro de Punho com Halter', 'Antebraço', 'Antebraço', 'Halter', 'Apoie o antebraço em uma superfície com o punho para fora da borda. Segure o halter com uma das extremidades e gire o punho de um lado para o outro lentamente. Trabalha os rotadores do antebraço (pronadores e supinadores).', false, true, NOW() WHERE NOT EXISTS (SELECT 1 FROM exercise_catalog WHERE name = 'Giro de Punho com Halter' AND category = 'Antebraço' AND is_custom = false);

INSERT INTO exercise_catalog (id, name, category, muscle, equipment, instructions, is_custom, is_active, created_at) SELECT gen_random_uuid(), 'Segurar Anilhas', 'Antebraço', 'Antebraço', 'Anilhas', 'Segure duas anilhas pela borda com os dedos por tempo determinado. Excelente para força de preensão e dedos. Pode ser feito em pé ao lado do corpo. Aumente gradualmente o tempo conforme melhora a resistência.', false, true, NOW() WHERE NOT EXISTS (SELECT 1 FROM exercise_catalog WHERE name = 'Segurar Anilhas' AND category = 'Antebraço' AND is_custom = false);

INSERT INTO exercise_catalog (id, name, category, muscle, equipment, instructions, is_custom, is_active, created_at) SELECT gen_random_uuid(), 'Sustentação na Barra Fixa', 'Antebraço', 'Antebraço', 'Barra fixa', 'Segure a barra fixa com pegada pronada ou supinada e sustente o peso do corpo pelo tempo determinado. Desenvolve força de preensão, antebraços e resistência. Ótimo exercício funcional, especialmente para quem quer progredir na barra fixa.', false, true, NOW() WHERE NOT EXISTS (SELECT 1 FROM exercise_catalog WHERE name = 'Sustentação na Barra Fixa' AND category = 'Antebraço' AND is_custom = false);

INSERT INTO exercise_catalog (id, name, category, muscle, equipment, instructions, is_custom, is_active, created_at) SELECT gen_random_uuid(), 'Rosca Pajé', 'Antebraço', 'Antebraço', 'Barra', 'Segure a barra com pegada supinada e realize a rosca em um ângulo diferente, com os cotovelos levemente elevados. A variação no ângulo muda o estímulo no bíceps braquial e no braquiorradial, trabalhando também os antebraços. Boa variação para quem já domina a rosca direta.', false, true, NOW() WHERE NOT EXISTS (SELECT 1 FROM exercise_catalog WHERE name = 'Rosca Pajé' AND category = 'Antebraço' AND is_custom = false);

INSERT INTO exercise_catalog (id, name, category, muscle, equipment, instructions, is_custom, is_active, created_at) SELECT gen_random_uuid(), 'Rosca Martelo Alternada com Foco na Pegada', 'Antebraço', 'Antebraço', 'Halteres', 'Execute a rosca martelo alternada com foco intencional em contrair os dedos e a preensão ao subir o halter. Segure no topo por 1-2 segundos aumentando a tensão no antebraço. Excelente para desenvolver preensão e braquiorradial.', false, true, NOW() WHERE NOT EXISTS (SELECT 1 FROM exercise_catalog WHERE name = 'Rosca Martelo Alternada com Foco na Pegada' AND category = 'Antebraço' AND is_custom = false);

INSERT INTO exercise_catalog (id, name, category, muscle, equipment, instructions, is_custom, is_active, created_at) SELECT gen_random_uuid(), 'Hand Gripper', 'Antebraço', 'Antebraço', 'Hand gripper', 'Segure o aparelho hand gripper na palma da mão e comprima completamente. Abra devagar para a posição inicial. Realize repetições ou isometria. Excelente para desenvolver força de preensão de forma isolada e pode ser feito em qualquer lugar.', false, true, NOW() WHERE NOT EXISTS (SELECT 1 FROM exercise_catalog WHERE name = 'Hand Gripper' AND category = 'Antebraço' AND is_custom = false);

-- QUADRÍCEPS
INSERT INTO exercise_catalog (id, name, category, muscle, equipment, instructions, is_custom, is_active, created_at) SELECT gen_random_uuid(), 'Agachamento Livre com Barra', 'Quadríceps', 'Quadríceps', 'Barra', 'Apoie a barra no trapézio com os pés na largura dos ombros. Desça controlado até as coxas ficarem paralelas ao chão mantendo o joelho alinhado com o pé e a lombar neutra. Empurre o chão com os pés para subir. Exercício composto fundamental para membros inferiores.', false, true, NOW() WHERE NOT EXISTS (SELECT 1 FROM exercise_catalog WHERE name = 'Agachamento Livre com Barra' AND category = 'Quadríceps' AND is_custom = false);

INSERT INTO exercise_catalog (id, name, category, muscle, equipment, instructions, is_custom, is_active, created_at) SELECT gen_random_uuid(), 'Leg Press 45°', 'Quadríceps', 'Quadríceps', 'Máquina', 'Sente na máquina de leg press 45 graus com os pés apoiados na plataforma na largura dos ombros. Desça flexionando os joelhos até 90 graus e empurre de volta sem travar os joelhos. Posição dos pés afeta quais músculos são mais recrutados.', false, true, NOW() WHERE NOT EXISTS (SELECT 1 FROM exercise_catalog WHERE name = 'Leg Press 45°' AND category = 'Quadríceps' AND is_custom = false);

INSERT INTO exercise_catalog (id, name, category, muscle, equipment, instructions, is_custom, is_active, created_at) SELECT gen_random_uuid(), 'Cadeira Extensora', 'Quadríceps', 'Quadríceps', 'Máquina', 'Ajuste a máquina para que o eixo de rotação fique alinhado com o joelho. Estenda os joelhos completamente contraindo o quadríceps no topo. Desça controlado. Exercício de isolamento para o quadríceps, especialmente o vasto medial (VMO).', false, true, NOW() WHERE NOT EXISTS (SELECT 1 FROM exercise_catalog WHERE name = 'Cadeira Extensora' AND category = 'Quadríceps' AND is_custom = false);

INSERT INTO exercise_catalog (id, name, category, muscle, equipment, instructions, is_custom, is_active, created_at) SELECT gen_random_uuid(), 'Agachamento Hack', 'Quadríceps', 'Quadríceps', 'Máquina', 'Posicione os ombros nos suportes da máquina hack squat com os pés na plataforma. Desça até as coxas ficarem paralelas ao chão e empurre de volta. A máquina guia o movimento e reduz o esforço lombar comparado ao agachamento livre.', false, true, NOW() WHERE NOT EXISTS (SELECT 1 FROM exercise_catalog WHERE name = 'Agachamento Hack' AND category = 'Quadríceps' AND is_custom = false);

INSERT INTO exercise_catalog (id, name, category, muscle, equipment, instructions, is_custom, is_active, created_at) SELECT gen_random_uuid(), 'Agachamento Búlgaro', 'Quadríceps', 'Quadríceps', 'Halteres', 'Posicione um pé atrás apoiado em um banco. Com o pé da frente firme no chão, desça o joelho traseiro em direção ao chão. Mantenha o tronco ereto e suba. Segure halteres para adicionar carga. Trabalha quadríceps e glúteos de forma unilateral.', false, true, NOW() WHERE NOT EXISTS (SELECT 1 FROM exercise_catalog WHERE name = 'Agachamento Búlgaro' AND category = 'Quadríceps' AND is_custom = false);

INSERT INTO exercise_catalog (id, name, category, muscle, equipment, instructions, is_custom, is_active, created_at) SELECT gen_random_uuid(), 'Passada / Avanço', 'Quadríceps', 'Quadríceps', 'Halteres', 'Fique em pé com os halteres na mão. Dê um passo longo à frente e desça o joelho traseiro em direção ao chão. Volte à posição inicial e alterne as pernas. Trabalha quadríceps, glúteos e melhora o equilíbrio. Pode ser feito andando ou estático.', false, true, NOW() WHERE NOT EXISTS (SELECT 1 FROM exercise_catalog WHERE name = 'Passada / Avanço' AND category = 'Quadríceps' AND is_custom = false);

INSERT INTO exercise_catalog (id, name, category, muscle, equipment, instructions, is_custom, is_active, created_at) SELECT gen_random_uuid(), 'Agachamento Frontal', 'Quadríceps', 'Quadríceps', 'Barra', 'Apoie a barra na frente dos ombros com os cotovelos elevados. Desça mantendo o tronco mais ereto que no agachamento convencional, até as coxas ficarem paralelas ao chão. Suba empurrando o chão. Enfatiza muito mais o quadríceps e demanda maior mobilidade de tornozelo e ombro.', false, true, NOW() WHERE NOT EXISTS (SELECT 1 FROM exercise_catalog WHERE name = 'Agachamento Frontal' AND category = 'Quadríceps' AND is_custom = false);

INSERT INTO exercise_catalog (id, name, category, muscle, equipment, instructions, is_custom, is_active, created_at) SELECT gen_random_uuid(), 'Agachamento Goblet', 'Quadríceps', 'Quadríceps', 'Kettlebell', 'Segure um kettlebell ou halter na frente do peito com as duas mãos. Pés na largura dos ombros ou um pouco mais abertos. Desça em agachamento profundo mantendo o tronco ereto e os joelhos alinhados com os pés. Suba empurrando o chão. Ótimo para iniciantes e mobilidade.', false, true, NOW() WHERE NOT EXISTS (SELECT 1 FROM exercise_catalog WHERE name = 'Agachamento Goblet' AND category = 'Quadríceps' AND is_custom = false);

INSERT INTO exercise_catalog (id, name, category, muscle, equipment, instructions, is_custom, is_active, created_at) SELECT gen_random_uuid(), 'Sissy Squat', 'Quadríceps', 'Quadríceps', 'Peso corporal', 'Fique em pé e segure algum suporte para equilíbrio. Eleve os calcanhares e incline o tronco para trás enquanto dobra os joelhos, descendo em direção ao chão. Suba contraindo o quadríceps. Exercício avançado que isola o quadríceps com grande amplitude de movimento.', false, true, NOW() WHERE NOT EXISTS (SELECT 1 FROM exercise_catalog WHERE name = 'Sissy Squat' AND category = 'Quadríceps' AND is_custom = false);

INSERT INTO exercise_catalog (id, name, category, muscle, equipment, instructions, is_custom, is_active, created_at) SELECT gen_random_uuid(), 'Agachamento no Smith Machine', 'Quadríceps', 'Quadríceps', 'Smith machine', 'Posicione a barra do Smith Machine nos ombros. Com os pés um pouco à frente do corpo, desça controlado até as coxas ficarem paralelas ao chão. Empurre de volta. O Smith Machine guia o movimento e é útil para trabalhar com mais segurança ou enfatizar diferentes ângulos.', false, true, NOW() WHERE NOT EXISTS (SELECT 1 FROM exercise_catalog WHERE name = 'Agachamento no Smith Machine' AND category = 'Quadríceps' AND is_custom = false);

-- POSTERIOR DE COXA
INSERT INTO exercise_catalog (id, name, category, muscle, equipment, instructions, is_custom, is_active, created_at) SELECT gen_random_uuid(), 'Stiff', 'Posterior de Coxa', 'Posterior de Coxa', 'Barra', 'Segure a barra na frente das coxas. Com os joelhos quase estendidos e fixos, incline o tronco para frente até a horizontal, descendo a barra pela perna até sentir o alongamento nos posteriores. Volte contraindo a lombar e posteriores. Exercício fundamental para posterior de coxa.', false, true, NOW() WHERE NOT EXISTS (SELECT 1 FROM exercise_catalog WHERE name = 'Stiff' AND category = 'Posterior de Coxa' AND is_custom = false);

INSERT INTO exercise_catalog (id, name, category, muscle, equipment, instructions, is_custom, is_active, created_at) SELECT gen_random_uuid(), 'Mesa Flexora', 'Posterior de Coxa', 'Posterior de Coxa', 'Máquina', 'Deite de bruços na mesa flexora com o eixo de rotação alinhado aos joelhos. Flexione os joelhos trazendo os calcanhares em direção aos glúteos. Contraia o posterior no topo e desça controlado. Exercício de isolamento eficaz para o bíceps femoral.', false, true, NOW() WHERE NOT EXISTS (SELECT 1 FROM exercise_catalog WHERE name = 'Mesa Flexora' AND category = 'Posterior de Coxa' AND is_custom = false);

INSERT INTO exercise_catalog (id, name, category, muscle, equipment, instructions, is_custom, is_active, created_at) SELECT gen_random_uuid(), 'Cadeira Flexora', 'Posterior de Coxa', 'Posterior de Coxa', 'Máquina', 'Sente na cadeira flexora com o eixo de rotação alinhado aos joelhos. Flexione os joelhos trazendo os calcanhares para baixo. Contraia o posterior no final e retorne controlado. Versão sentada que muda levemente o ângulo de trabalho do bíceps femoral.', false, true, NOW() WHERE NOT EXISTS (SELECT 1 FROM exercise_catalog WHERE name = 'Cadeira Flexora' AND category = 'Posterior de Coxa' AND is_custom = false);

INSERT INTO exercise_catalog (id, name, category, muscle, equipment, instructions, is_custom, is_active, created_at) SELECT gen_random_uuid(), 'Flexora Vertical', 'Posterior de Coxa', 'Posterior de Coxa', 'Máquina', 'Fique em pé na máquina flexora vertical com o joelho alinhado ao eixo. Flexione um joelho de cada vez trazendo o calcanhar em direção ao glúteo. Desça controlado. Permite trabalhar unilateralmente com boa amplitude, útil para reabilitação.', false, true, NOW() WHERE NOT EXISTS (SELECT 1 FROM exercise_catalog WHERE name = 'Flexora Vertical' AND category = 'Posterior de Coxa' AND is_custom = false);

INSERT INTO exercise_catalog (id, name, category, muscle, equipment, instructions, is_custom, is_active, created_at) SELECT gen_random_uuid(), 'Levantamento Terra Romeno', 'Posterior de Coxa', 'Posterior de Coxa', 'Barra', 'Segure a barra na frente das coxas com pegada pronada. Com joelhos levemente flexionados e fixos, incline o tronco para frente deslizando a barra pela perna. Sinta o alongamento nos posteriores e volte contraindo glúteos e posteriores. Foco em posterior e glúteos.', false, true, NOW() WHERE NOT EXISTS (SELECT 1 FROM exercise_catalog WHERE name = 'Levantamento Terra Romeno' AND category = 'Posterior de Coxa' AND is_custom = false);

INSERT INTO exercise_catalog (id, name, category, muscle, equipment, instructions, is_custom, is_active, created_at) SELECT gen_random_uuid(), 'Flexão de Pernas na Bola Suíça', 'Posterior de Coxa', 'Posterior de Coxa', 'Bola suíça', 'Deite de costas e coloque os calcanhares sobre a bola suíça. Eleve o quadril e role a bola em direção ao corpo flexionando os joelhos. Estenda de volta controlado. Trabalha os posteriores de forma funcional, exigindo também estabilidade do core.', false, true, NOW() WHERE NOT EXISTS (SELECT 1 FROM exercise_catalog WHERE name = 'Flexão de Pernas na Bola Suíça' AND category = 'Posterior de Coxa' AND is_custom = false);

INSERT INTO exercise_catalog (id, name, category, muscle, equipment, instructions, is_custom, is_active, created_at) SELECT gen_random_uuid(), 'Bom Dia com Foco em Posterior', 'Posterior de Coxa', 'Posterior de Coxa', 'Barra', 'Apoie a barra nos ombros. Com os joelhos levemente flexionados e fixos, incline o tronco para frente mantendo a lombar neutra até sentir o alongamento nos posteriores de coxa. Volte contraindo os posteriores e glúteos. Variação do bom dia com ênfase no isquiotibial.', false, true, NOW() WHERE NOT EXISTS (SELECT 1 FROM exercise_catalog WHERE name = 'Bom Dia com Foco em Posterior' AND category = 'Posterior de Coxa' AND is_custom = false);

INSERT INTO exercise_catalog (id, name, category, muscle, equipment, instructions, is_custom, is_active, created_at) SELECT gen_random_uuid(), 'Flexão de Pernas no Cabo', 'Posterior de Coxa', 'Posterior de Coxa', 'Polia', 'Prenda a tornozeleira no cabo baixo e fixe no tornozelo. Fique de pé de frente para a polia e flexione o joelho trazendo o calcanhar para os glúteos. Desça controlado. O cabo mantém tensão constante durante o movimento. Execute dos dois lados.', false, true, NOW() WHERE NOT EXISTS (SELECT 1 FROM exercise_catalog WHERE name = 'Flexão de Pernas no Cabo' AND category = 'Posterior de Coxa' AND is_custom = false);

INSERT INTO exercise_catalog (id, name, category, muscle, equipment, instructions, is_custom, is_active, created_at) SELECT gen_random_uuid(), 'Glute Ham Raise', 'Posterior de Coxa', 'Posterior de Coxa', 'Banco GHR', 'Posicione os pés no suporte do banco GHR com os joelhos na almofada. Incline o tronco para frente controlando com os posteriores e suba de volta contraindo os isquiotibiais. Exercício avançado que trabalha os posteriores na extensão do quadril e flexão do joelho simultaneamente.', false, true, NOW() WHERE NOT EXISTS (SELECT 1 FROM exercise_catalog WHERE name = 'Glute Ham Raise' AND category = 'Posterior de Coxa' AND is_custom = false);

INSERT INTO exercise_catalog (id, name, category, muscle, equipment, instructions, is_custom, is_active, created_at) SELECT gen_random_uuid(), 'Stiff Unilateral', 'Posterior de Coxa', 'Posterior de Coxa', 'Halter', 'Fique em pé em um pé só segurando um halter. Incline o tronco para frente mantendo a lombar neutra enquanto a perna livre vai para trás. Desça até sentir o alongamento no posterior e volte. Trabalha o posterior de coxa de forma unilateral melhorando equilíbrio.', false, true, NOW() WHERE NOT EXISTS (SELECT 1 FROM exercise_catalog WHERE name = 'Stiff Unilateral' AND category = 'Posterior de Coxa' AND is_custom = false);

-- GLÚTEOS
INSERT INTO exercise_catalog (id, name, category, muscle, equipment, instructions, is_custom, is_active, created_at) SELECT gen_random_uuid(), 'Elevação Pélvica', 'Glúteos', 'Glúteos', 'Barra', 'Apoie a parte superior das costas em um banco. Posicione a barra no quadril protegida por uma esponja. Com os pés apoiados no chão, empurre o quadril para cima contraindo os glúteos. Segure 1-2 segundos no topo e desça. Um dos melhores exercícios para ativar o glúteo máximo.', false, true, NOW() WHERE NOT EXISTS (SELECT 1 FROM exercise_catalog WHERE name = 'Elevação Pélvica' AND category = 'Glúteos' AND is_custom = false);

INSERT INTO exercise_catalog (id, name, category, muscle, equipment, instructions, is_custom, is_active, created_at) SELECT gen_random_uuid(), 'Agachamento Sumô', 'Glúteos', 'Glúteos', 'Barra', 'Posicione os pés mais afastados que os ombros com os dedos apontados para fora. Com a barra nos ombros, desça em agachamento mantendo o tronco ereto. Suba empurrando os pés para fora. O posicionamento largo enfatiza adutores e glúteos mais que o agachamento convencional.', false, true, NOW() WHERE NOT EXISTS (SELECT 1 FROM exercise_catalog WHERE name = 'Agachamento Sumô' AND category = 'Glúteos' AND is_custom = false);

INSERT INTO exercise_catalog (id, name, category, muscle, equipment, instructions, is_custom, is_active, created_at) SELECT gen_random_uuid(), 'Glúteo Coice no Cabo', 'Glúteos', 'Glúteos', 'Polia', 'Prenda a tornozeleira no cabo baixo. Fique de frente para a polia com leve inclinação do tronco. Empurre a perna para trás estendendo o quadril, contraindo o glúteo. Retorne controlado. Isola o glúteo máximo de forma eficaz. Execute dos dois lados.', false, true, NOW() WHERE NOT EXISTS (SELECT 1 FROM exercise_catalog WHERE name = 'Glúteo Coice no Cabo' AND category = 'Glúteos' AND is_custom = false);

INSERT INTO exercise_catalog (id, name, category, muscle, equipment, instructions, is_custom, is_active, created_at) SELECT gen_random_uuid(), 'Cadeira Abdutora', 'Glúteos', 'Glúteos', 'Máquina', 'Sente na máquina abdutora com os joelhos sobre as almofadas. Empurre as pernas para fora afastando os joelhos e retorne controlado. Trabalha o glúteo médio e os abdutores do quadril. Importante para estabilidade do joelho e postura.', false, true, NOW() WHERE NOT EXISTS (SELECT 1 FROM exercise_catalog WHERE name = 'Cadeira Abdutora' AND category = 'Glúteos' AND is_custom = false);

INSERT INTO exercise_catalog (id, name, category, muscle, equipment, instructions, is_custom, is_active, created_at) SELECT gen_random_uuid(), 'Abdução de Quadril no Cabo', 'Glúteos', 'Glúteos', 'Polia', 'Prenda a tornozeleira no cabo baixo no tornozelo externo. Fique ao lado da polia e eleve a perna lateralmente afastando o quadril. Contraia o glúteo médio no topo e retorne controlado. O cabo mantém tensão constante. Execute dos dois lados.', false, true, NOW() WHERE NOT EXISTS (SELECT 1 FROM exercise_catalog WHERE name = 'Abdução de Quadril no Cabo' AND category = 'Glúteos' AND is_custom = false);

INSERT INTO exercise_catalog (id, name, category, muscle, equipment, instructions, is_custom, is_active, created_at) SELECT gen_random_uuid(), 'Glúteo na Máquina', 'Glúteos', 'Glúteos', 'Máquina', 'Ajuste a máquina de extensão de quadril. Apoie a almofada no joelho ou panturrilha e empurre a perna para trás estendendo o quadril, contraindo o glúteo. Retorne controlado. Isola o glúteo máximo de forma segura e controlada.', false, true, NOW() WHERE NOT EXISTS (SELECT 1 FROM exercise_catalog WHERE name = 'Glúteo na Máquina' AND category = 'Glúteos' AND is_custom = false);

INSERT INTO exercise_catalog (id, name, category, muscle, equipment, instructions, is_custom, is_active, created_at) SELECT gen_random_uuid(), 'Elevação Pélvica Unilateral', 'Glúteos', 'Glúteos', 'Peso corporal', 'Deite de costas com um joelho flexionado e o outro estendido. Eleve o quadril usando apenas o pé apoiado, contraindo o glúteo do lado de trabalho. Segure 2 segundos no topo. Exercício unilateral que identifica e corrige desequilíbrios entre glúteos.', false, true, NOW() WHERE NOT EXISTS (SELECT 1 FROM exercise_catalog WHERE name = 'Elevação Pélvica Unilateral' AND category = 'Glúteos' AND is_custom = false);

INSERT INTO exercise_catalog (id, name, category, muscle, equipment, instructions, is_custom, is_active, created_at) SELECT gen_random_uuid(), 'Agachamento Búlgaro com Foco em Glúteo', 'Glúteos', 'Glúteos', 'Halteres', 'Posicione um pé apoiado atrás em um banco. Com o pé da frente mais afastado, desça inclinando levemente o tronco para frente para aumentar o recrutamento do glúteo. Suba empurrando o calcanhar no chão. O posicionamento do pé e inclinação mudam o foco de quadríceps para glúteos.', false, true, NOW() WHERE NOT EXISTS (SELECT 1 FROM exercise_catalog WHERE name = 'Agachamento Búlgaro com Foco em Glúteo' AND category = 'Glúteos' AND is_custom = false);

INSERT INTO exercise_catalog (id, name, category, muscle, equipment, instructions, is_custom, is_active, created_at) SELECT gen_random_uuid(), 'Extensão de Quadril no Banco 45°', 'Glúteos', 'Glúteos', 'Banco 45°', 'Posicione o quadril na almofada do banco de 45 graus com os pés no suporte. Incline o tronco para baixo e suba estendendo o quadril completamente, contraindo os glúteos e posteriores. Evite hipere...extensão lombar. Pode segurar um disco para aumentar a dificuldade.', false, true, NOW() WHERE NOT EXISTS (SELECT 1 FROM exercise_catalog WHERE name = 'Extensão de Quadril no Banco 45°' AND category = 'Glúteos' AND is_custom = false);

INSERT INTO exercise_catalog (id, name, category, muscle, equipment, instructions, is_custom, is_active, created_at) SELECT gen_random_uuid(), 'Passada para Trás', 'Glúteos', 'Glúteos', 'Halteres', 'Fique em pé com os halteres na mão. Dê um passo longo para trás e desça o joelho traseiro em direção ao chão. Empurre o pé da frente para voltar à posição inicial. A passada para trás recruta mais o glúteo do que a passada para frente. Alterne as pernas.', false, true, NOW() WHERE NOT EXISTS (SELECT 1 FROM exercise_catalog WHERE name = 'Passada para Trás' AND category = 'Glúteos' AND is_custom = false);

-- PANTURRILHAS
INSERT INTO exercise_catalog (id, name, category, muscle, equipment, instructions, is_custom, is_active, created_at) SELECT gen_random_uuid(), 'Gêmeos em Pé', 'Panturrilhas', 'Panturrilha', 'Máquina', 'Posicione os ombros sob as almofadas da máquina. Com as pontas dos pés no step, desça os calcanhares abaixo do nível do step para o alongamento máximo. Suba nas pontas dos pés, contraindo a panturrilha no topo. Desça controlado para o alongamento.', false, true, NOW() WHERE NOT EXISTS (SELECT 1 FROM exercise_catalog WHERE name = 'Gêmeos em Pé' AND category = 'Panturrilhas' AND is_custom = false);

INSERT INTO exercise_catalog (id, name, category, muscle, equipment, instructions, is_custom, is_active, created_at) SELECT gen_random_uuid(), 'Gêmeos Sentado', 'Panturrilhas', 'Panturrilha', 'Máquina', 'Sente na máquina de panturrilha sentado com as almofadas sobre os joelhos e as pontas dos pés no step. Eleve os calcanhares subindo nas pontas dos pés e contraia. Desça até o alongamento máximo. O exercício sentado enfatiza o músculo sóleo (mais profundo).', false, true, NOW() WHERE NOT EXISTS (SELECT 1 FROM exercise_catalog WHERE name = 'Gêmeos Sentado' AND category = 'Panturrilhas' AND is_custom = false);

INSERT INTO exercise_catalog (id, name, category, muscle, equipment, instructions, is_custom, is_active, created_at) SELECT gen_random_uuid(), 'Panturrilha no Leg Press', 'Panturrilhas', 'Panturrilha', 'Máquina', 'Sente no leg press mas coloque apenas a frente dos pés na borda inferior da plataforma. Estenda os tornozelos empurrando a plataforma com as pontas dos pés e retorne. O leg press permite maior carga e amplitude de movimento para a panturrilha.', false, true, NOW() WHERE NOT EXISTS (SELECT 1 FROM exercise_catalog WHERE name = 'Panturrilha no Leg Press' AND category = 'Panturrilhas' AND is_custom = false);

INSERT INTO exercise_catalog (id, name, category, muscle, equipment, instructions, is_custom, is_active, created_at) SELECT gen_random_uuid(), 'Elevação de Panturrilha Unilateral', 'Panturrilhas', 'Panturrilha', 'Peso corporal', 'Apoie-se em alguma superfície para equilíbrio. Eleve-se na ponta de um pé só contraindo a panturrilha. Desça lentamente até o calcanhar ficar abaixo do nível de apoio. Execute dos dois lados. O exercício unilateral aumenta a intensidade e corrige desequilíbrios.', false, true, NOW() WHERE NOT EXISTS (SELECT 1 FROM exercise_catalog WHERE name = 'Elevação de Panturrilha Unilateral' AND category = 'Panturrilhas' AND is_custom = false);

INSERT INTO exercise_catalog (id, name, category, muscle, equipment, instructions, is_custom, is_active, created_at) SELECT gen_random_uuid(), 'Panturrilha no Hack Machine', 'Panturrilhas', 'Panturrilha', 'Máquina', 'Na máquina hack, posicione apenas as pontas dos pés na plataforma com os calcanhares para fora. Eleve nos tornozelos contraindo a panturrilha e desça controlado. A posição das pontas dos pés no hack permite amplitude similar à máquina de gêmeos em pé.', false, true, NOW() WHERE NOT EXISTS (SELECT 1 FROM exercise_catalog WHERE name = 'Panturrilha no Hack Machine' AND category = 'Panturrilhas' AND is_custom = false);

INSERT INTO exercise_catalog (id, name, category, muscle, equipment, instructions, is_custom, is_active, created_at) SELECT gen_random_uuid(), 'Panturrilha Burrinho Livre', 'Panturrilhas', 'Panturrilha', 'Peso corporal', 'Incline o tronco para frente apoiando as mãos em uma superfície estável. Peça a um parceiro para sentar nas suas costas ou adicione um colete com peso. Eleve-se nas pontas dos pés contraindo a panturrilha. Desça controlado. Versão livre do exercício burrinho.', false, true, NOW() WHERE NOT EXISTS (SELECT 1 FROM exercise_catalog WHERE name = 'Panturrilha Burrinho Livre' AND category = 'Panturrilhas' AND is_custom = false);

INSERT INTO exercise_catalog (id, name, category, muscle, equipment, instructions, is_custom, is_active, created_at) SELECT gen_random_uuid(), 'Elevação de Panturrilha em Pé com Halteres', 'Panturrilhas', 'Panturrilha', 'Halteres', 'Segure halteres em cada mão ao lado do corpo. Com as pontas dos pés em um step ou degrau, desça os calcanhares e suba nas pontas dos pés contraindo a panturrilha. O step aumenta a amplitude de movimento. Desça controlado para o alongamento máximo.', false, true, NOW() WHERE NOT EXISTS (SELECT 1 FROM exercise_catalog WHERE name = 'Elevação de Panturrilha em Pé com Halteres' AND category = 'Panturrilhas' AND is_custom = false);

INSERT INTO exercise_catalog (id, name, category, muscle, equipment, instructions, is_custom, is_active, created_at) SELECT gen_random_uuid(), 'Panturrilha no Smith com Step', 'Panturrilhas', 'Panturrilha', 'Smith machine', 'Coloque um step embaixo do Smith Machine. Posicione a barra nos ombros e as pontas dos pés no step. Suba nas pontas dos pés contraindo a panturrilha e desça controlado até o calcanhar ficar abaixo do step. O Smith permite sobrecarga segura sem spotter.', false, true, NOW() WHERE NOT EXISTS (SELECT 1 FROM exercise_catalog WHERE name = 'Panturrilha no Smith com Step' AND category = 'Panturrilhas' AND is_custom = false);

INSERT INTO exercise_catalog (id, name, category, muscle, equipment, instructions, is_custom, is_active, created_at) SELECT gen_random_uuid(), 'Elevação de Panturrilha Sentado com Halter', 'Panturrilhas', 'Panturrilha', 'Halter', 'Sente em um banco com os pés apoiados em um step. Coloque um halter sobre os joelhos. Eleve os calcanhares subindo nas pontas dos pés e contraia. Desça até o alongamento máximo. Trabalha especialmente o sóleo por causa do joelho flexionado.', false, true, NOW() WHERE NOT EXISTS (SELECT 1 FROM exercise_catalog WHERE name = 'Elevação de Panturrilha Sentado com Halter' AND category = 'Panturrilhas' AND is_custom = false);

INSERT INTO exercise_catalog (id, name, category, muscle, equipment, instructions, is_custom, is_active, created_at) SELECT gen_random_uuid(), 'Caminhada na Ponta dos Pés', 'Panturrilhas', 'Panturrilha', 'Peso corporal', 'Eleve os calcanhares e caminhe na ponta dos pés por uma distância determinada. Mantenha a contração constante na panturrilha durante todo o percurso. Exercício funcional que trabalha a resistência da panturrilha e o equilíbrio. Pode ser feito com halteres para aumentar a dificuldade.', false, true, NOW() WHERE NOT EXISTS (SELECT 1 FROM exercise_catalog WHERE name = 'Caminhada na Ponta dos Pés' AND category = 'Panturrilhas' AND is_custom = false);

-- ABDÔMEN
INSERT INTO exercise_catalog (id, name, category, muscle, equipment, instructions, is_custom, is_active, created_at) SELECT gen_random_uuid(), 'Abdominal Supra', 'Abdômen', 'Abdômen', 'Peso corporal', 'Deite de costas com os joelhos flexionados e pés apoiados no chão. Com as mãos atrás da cabeça ou cruzadas no peito, eleve apenas o tronco superior do chão contraindo o abdômen. Não puxe o pescoço. Desça controlado. Trabalha o reto abdominal superior.', false, true, NOW() WHERE NOT EXISTS (SELECT 1 FROM exercise_catalog WHERE name = 'Abdominal Supra' AND category = 'Abdômen' AND is_custom = false);

INSERT INTO exercise_catalog (id, name, category, muscle, equipment, instructions, is_custom, is_active, created_at) SELECT gen_random_uuid(), 'Abdominal Infra', 'Abdômen', 'Abdômen', 'Peso corporal', 'Deite de costas com as mãos sob o glúteo para suporte. Eleve as pernas do chão até 90 graus e desça de volta sem tocar o chão. Ou eleve os joelhos ao peito. Trabalha o reto abdominal inferior, uma área de difícil isolamento.', false, true, NOW() WHERE NOT EXISTS (SELECT 1 FROM exercise_catalog WHERE name = 'Abdominal Infra' AND category = 'Abdômen' AND is_custom = false);

INSERT INTO exercise_catalog (id, name, category, muscle, equipment, instructions, is_custom, is_active, created_at) SELECT gen_random_uuid(), 'Prancha Abdominal Tradicional', 'Abdômen', 'Abdômen', 'Peso corporal', 'Apoie os antebraços e as pontas dos pés no chão. Eleve o corpo mantendo-o em linha reta da cabeça aos calcanhares. Contraia o abdômen, glúteos e quadríceps. Segure a posição pelo tempo determinado. Exercício isométrico completo para o core.', false, true, NOW() WHERE NOT EXISTS (SELECT 1 FROM exercise_catalog WHERE name = 'Prancha Abdominal Tradicional' AND category = 'Abdômen' AND is_custom = false);

INSERT INTO exercise_catalog (id, name, category, muscle, equipment, instructions, is_custom, is_active, created_at) SELECT gen_random_uuid(), 'Abdominal na Polia Alta', 'Abdômen', 'Abdômen', 'Polia', 'Ajoelhe-se de frente para a polia alta e segure a corda atrás da cabeça. Contraia o abdômen flexionando o tronco em direção aos joelhos. Retorne controlado sem arquear demais a lombar. Permite adicionar carga progressiva ao abdominal, ótimo para ganho de massa abdominal.', false, true, NOW() WHERE NOT EXISTS (SELECT 1 FROM exercise_catalog WHERE name = 'Abdominal na Polia Alta' AND category = 'Abdômen' AND is_custom = false);

INSERT INTO exercise_catalog (id, name, category, muscle, equipment, instructions, is_custom, is_active, created_at) SELECT gen_random_uuid(), 'Abdominal Oblíquo Alternado', 'Abdômen', 'Abdômen', 'Peso corporal', 'Deite de costas com os joelhos flexionados. Leve o cotovelo direito em direção ao joelho esquerdo e vice-versa, alternando os lados. Eleve o tronco em rotação contraindo o oblíquo. Trabalha os oblíquos interno e externo, responsáveis pela cintura.', false, true, NOW() WHERE NOT EXISTS (SELECT 1 FROM exercise_catalog WHERE name = 'Abdominal Oblíquo Alternado' AND category = 'Abdômen' AND is_custom = false);

INSERT INTO exercise_catalog (id, name, category, muscle, equipment, instructions, is_custom, is_active, created_at) SELECT gen_random_uuid(), 'Elevação de Pernas na Barra Fixa', 'Abdômen', 'Abdômen', 'Barra fixa', 'Segure a barra fixa com os braços estendidos. Eleve as pernas estendidas ou com joelhos flexionados até a altura da cintura ou acima. Contraia o abdômen no topo e desça controlado sem balançar. Exercício avançado que trabalha reto abdominal e flexores do quadril.', false, true, NOW() WHERE NOT EXISTS (SELECT 1 FROM exercise_catalog WHERE name = 'Elevação de Pernas na Barra Fixa' AND category = 'Abdômen' AND is_custom = false);

INSERT INTO exercise_catalog (id, name, category, muscle, equipment, instructions, is_custom, is_active, created_at) SELECT gen_random_uuid(), 'Abdominal Infra no Banco Inclinado', 'Abdômen', 'Abdômen', 'Banco inclinado', 'Sente no banco inclinado segurando as bordas atrás. Eleve os joelhos em direção ao peito e abaixe controlado. O ângulo inclinado aumenta a dificuldade e amplitude do movimento. Trabalha o reto abdominal inferior com sobrecarga adicional.', false, true, NOW() WHERE NOT EXISTS (SELECT 1 FROM exercise_catalog WHERE name = 'Abdominal Infra no Banco Inclinado' AND category = 'Abdômen' AND is_custom = false);

INSERT INTO exercise_catalog (id, name, category, muscle, equipment, instructions, is_custom, is_active, created_at) SELECT gen_random_uuid(), 'Prancha Lateral Dinâmica', 'Abdômen', 'Abdômen', 'Peso corporal', 'Posicione-se na prancha lateral com o antebraço apoiado. Desça o quadril até quase tocar o chão e suba de volta. Movimento dinâmico que trabalha os oblíquos com maior intensidade que a prancha estática. Execute dos dois lados.', false, true, NOW() WHERE NOT EXISTS (SELECT 1 FROM exercise_catalog WHERE name = 'Prancha Lateral Dinâmica' AND category = 'Abdômen' AND is_custom = false);

INSERT INTO exercise_catalog (id, name, category, muscle, equipment, instructions, is_custom, is_active, created_at) SELECT gen_random_uuid(), 'Abdominal Rodinha', 'Abdômen', 'Abdômen', 'Roda abdominal', 'Ajoelhe-se e segure a roda abdominal. Role para frente estendendo o corpo até quase tocar o chão com o quadril nivelado. Puxe de volta contraindo o abdômen. Exercício avançado que trabalha o core completo, especialmente reto abdominal e serrátil.', false, true, NOW() WHERE NOT EXISTS (SELECT 1 FROM exercise_catalog WHERE name = 'Abdominal Rodinha' AND category = 'Abdômen' AND is_custom = false);

INSERT INTO exercise_catalog (id, name, category, muscle, equipment, instructions, is_custom, is_active, created_at) SELECT gen_random_uuid(), 'Abdominal Infra no Banco Paralelo', 'Abdômen', 'Abdômen', 'Banco paralelo', 'Segure as barras paralelas e apoie o peso nos braços. Eleve os joelhos ao peito ou as pernas estendidas até a horizontal. Desça controlado. Permite grande amplitude de movimento e é ótimo para a parte inferior do abdômen.', false, true, NOW() WHERE NOT EXISTS (SELECT 1 FROM exercise_catalog WHERE name = 'Abdominal Infra no Banco Paralelo' AND category = 'Abdômen' AND is_custom = false);
